import type { Skill } from '@/types/skills';

/** Sample skill set inspired by League of Legends */
export const sampleSkills: Skill[] = [
  {
    id: 'fireball',
    name: 'Fireball',
    key: 'Q',
    description: 'Launch a fireball in the target direction, dealing 80 magical damage to the first enemy hit.',
    cooldown: 6,
    manaCost: 50,
    range: 15,
    targetType: 'direction',
    value: 80,
    damageType: 'magical',
    effectType: 'projectile',
    effectColor: '#ff6b35',
    animation: 'cast',
    icon: '/skills/fireball.png',
  },
  {
    id: 'ice_shield',
    name: 'Ice Shield',
    key: 'W',
    description: 'Create a protective ice shield that absorbs 150 damage for 3 seconds.',
    cooldown: 12,
    manaCost: 70,
    range: 0,
    targetType: 'self',
    value: 150,
    damageType: 'magical',
    effectType: 'shield',
    effectColor: '#4ecdc4',
    animation: 'buff',
    icon: '/skills/ice-shield.png',
  },
  {
    id: 'lightning_dash',
    name: 'Lightning Dash',
    key: 'E',
    description: 'Dash forward in a burst of lightning, dealing 60 magical damage to enemies passed through.',
    cooldown: 10,
    manaCost: 60,
    range: 8,
    targetType: 'direction',
    value: 60,
    damageType: 'magical',
    effectType: 'dash',
    effectColor: '#f7b731',
    animation: 'dash',
    icon: '/skills/lightning-dash.png',
  },
  {
    id: 'meteor_strike',
    name: 'Meteor Strike',
    key: 'R',
    description: 'Call down a meteor at the target location, dealing 200 magical damage in a large area.',
    cooldown: 80,
    manaCost: 100,
    range: 20,
    targetType: 'point',
    radius: 5,
    value: 200,
    damageType: 'magical',
    effectType: 'area',
    effectColor: '#ee5a6f',
    animation: 'ultimate',
    icon: '/skills/meteor-strike.png',
  },
];

/** Initial player stats */
export const initialPlayerStats = {
  health: 600,
  maxHealth: 600,
  mana: 400,
  maxMana: 400,
  healthRegen: 5,
  manaRegen: 10,
  movementSpeed: 5,
  attackDamage: 50,
  abilityPower: 100,
  armor: 30,
  magicResist: 30,
};
